/*
 * ELEMENTS API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ElementsSDK.Api;
using ElementsSDK.Model;
using ElementsSDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ElementsSDK.Test.Model
{
    /// <summary>
    ///  Class for testing Alert
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AlertTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Alert
        //private Alert instance;

        public AlertTests()
        {
            // TODO uncomment below to create an instance of Alert
            //instance = new Alert();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Alert
        /// </summary>
        [Fact]
        public void AlertInstanceTest()
        {
            // TODO uncomment below to test "IsType" Alert
            //Assert.IsType<Alert>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Fact]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }
        /// <summary>
        /// Test the property 'Level'
        /// </summary>
        [Fact]
        public void LevelTest()
        {
            // TODO unit test for the property 'Level'
        }
        /// <summary>
        /// Test the property 'IsOpen'
        /// </summary>
        [Fact]
        public void IsOpenTest()
        {
            // TODO unit test for the property 'IsOpen'
        }
        /// <summary>
        /// Test the property 'Node'
        /// </summary>
        [Fact]
        public void NodeTest()
        {
            // TODO unit test for the property 'Node'
        }
        /// <summary>
        /// Test the property 'OpenedAt'
        /// </summary>
        [Fact]
        public void OpenedAtTest()
        {
            // TODO unit test for the property 'OpenedAt'
        }
        /// <summary>
        /// Test the property 'ClosedAt'
        /// </summary>
        [Fact]
        public void ClosedAtTest()
        {
            // TODO unit test for the property 'ClosedAt'
        }
        /// <summary>
        /// Test the property 'Duration'
        /// </summary>
        [Fact]
        public void DurationTest()
        {
            // TODO unit test for the property 'Duration'
        }

    }

}
