/*
 * ELEMENTS API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ElementsSDK.Api;
using ElementsSDK.Model;
using ElementsSDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ElementsSDK.Test.Model
{
    /// <summary>
    ///  Class for testing AssetBackup
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AssetBackupTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AssetBackup
        //private AssetBackup instance;

        public AssetBackupTests()
        {
            // TODO uncomment below to create an instance of AssetBackup
            //instance = new AssetBackup();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AssetBackup
        /// </summary>
        [Fact]
        public void AssetBackupInstanceTest()
        {
            // TODO uncomment below to test "IsType" AssetBackup
            //Assert.IsType<AssetBackup>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'TapeFile'
        /// </summary>
        [Fact]
        public void TapeFileTest()
        {
            // TODO unit test for the property 'TapeFile'
        }
        /// <summary>
        /// Test the property 'Asset'
        /// </summary>
        [Fact]
        public void AssetTest()
        {
            // TODO unit test for the property 'Asset'
        }
        /// <summary>
        /// Test the property 'SearchHighlight'
        /// </summary>
        [Fact]
        public void SearchHighlightTest()
        {
            // TODO unit test for the property 'SearchHighlight'
        }
        /// <summary>
        /// Test the property 'CustomFieldsSnapshot'
        /// </summary>
        [Fact]
        public void CustomFieldsSnapshotTest()
        {
            // TODO unit test for the property 'CustomFieldsSnapshot'
        }

    }

}
