/*
 * ELEMENTS API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ElementsSDK.Api;
using ElementsSDK.Model;
using ElementsSDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ElementsSDK.Test.Model
{
    /// <summary>
    ///  Class for testing AssetPartialUpdate
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AssetPartialUpdateTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AssetPartialUpdate
        //private AssetPartialUpdate instance;

        public AssetPartialUpdateTests()
        {
            // TODO uncomment below to create an instance of AssetPartialUpdate
            //instance = new AssetPartialUpdate();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AssetPartialUpdate
        /// </summary>
        [Fact]
        public void AssetPartialUpdateInstanceTest()
        {
            // TODO uncomment below to test "IsType" AssetPartialUpdate
            //Assert.IsType<AssetPartialUpdate>(instance);
        }


        /// <summary>
        /// Test the property 'CustomFields'
        /// </summary>
        [Fact]
        public void CustomFieldsTest()
        {
            // TODO unit test for the property 'CustomFields'
        }
        /// <summary>
        /// Test the property 'Tags'
        /// </summary>
        [Fact]
        public void TagsTest()
        {
            // TODO unit test for the property 'Tags'
        }
        /// <summary>
        /// Test the property 'Set'
        /// </summary>
        [Fact]
        public void SetTest()
        {
            // TODO unit test for the property 'Set'
        }

    }

}
