/*
 * ELEMENTS API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ElementsSDK.Api;
using ElementsSDK.Model;
using ElementsSDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ElementsSDK.Test.Model
{
    /// <summary>
    ///  Class for testing AssetProjectLink
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AssetProjectLinkTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AssetProjectLink
        //private AssetProjectLink instance;

        public AssetProjectLinkTests()
        {
            // TODO uncomment below to create an instance of AssetProjectLink
            //instance = new AssetProjectLink();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AssetProjectLink
        /// </summary>
        [Fact]
        public void AssetProjectLinkInstanceTest()
        {
            // TODO uncomment below to test "IsType" AssetProjectLink
            //Assert.IsType<AssetProjectLink>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Project'
        /// </summary>
        [Fact]
        public void ProjectTest()
        {
            // TODO unit test for the property 'Project'
        }
        /// <summary>
        /// Test the property 'SequenceName'
        /// </summary>
        [Fact]
        public void SequenceNameTest()
        {
            // TODO unit test for the property 'SequenceName'
        }
        /// <summary>
        /// Test the property 'Asset'
        /// </summary>
        [Fact]
        public void AssetTest()
        {
            // TODO unit test for the property 'Asset'
        }

    }

}
