/*
 * ELEMENTS API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ElementsSDK.Api;
using ElementsSDK.Model;
using ElementsSDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ElementsSDK.Test.Model
{
    /// <summary>
    ///  Class for testing CommentPartialUpdate
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CommentPartialUpdateTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CommentPartialUpdate
        //private CommentPartialUpdate instance;

        public CommentPartialUpdateTests()
        {
            // TODO uncomment below to create an instance of CommentPartialUpdate
            //instance = new CommentPartialUpdate();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CommentPartialUpdate
        /// </summary>
        [Fact]
        public void CommentPartialUpdateInstanceTest()
        {
            // TODO uncomment below to test "IsType" CommentPartialUpdate
            //Assert.IsType<CommentPartialUpdate>(instance);
        }


        /// <summary>
        /// Test the property 'Assignee'
        /// </summary>
        [Fact]
        public void AssigneeTest()
        {
            // TODO unit test for the property 'Assignee'
        }
        /// <summary>
        /// Test the property 'User'
        /// </summary>
        [Fact]
        public void UserTest()
        {
            // TODO unit test for the property 'User'
        }
        /// <summary>
        /// Test the property 'Drawing'
        /// </summary>
        [Fact]
        public void DrawingTest()
        {
            // TODO unit test for the property 'Drawing'
        }
        /// <summary>
        /// Test the property 'Tags'
        /// </summary>
        [Fact]
        public void TagsTest()
        {
            // TODO unit test for the property 'Tags'
        }
        /// <summary>
        /// Test the property 'Text'
        /// </summary>
        [Fact]
        public void TextTest()
        {
            // TODO unit test for the property 'Text'
        }
        /// <summary>
        /// Test the property 'Time'
        /// </summary>
        [Fact]
        public void TimeTest()
        {
            // TODO unit test for the property 'Time'
        }
        /// <summary>
        /// Test the property 'IsCloud'
        /// </summary>
        [Fact]
        public void IsCloudTest()
        {
            // TODO unit test for the property 'IsCloud'
        }
        /// <summary>
        /// Test the property 'Resolved'
        /// </summary>
        [Fact]
        public void ResolvedTest()
        {
            // TODO unit test for the property 'Resolved'
        }
        /// <summary>
        /// Test the property 'ResolvedDate'
        /// </summary>
        [Fact]
        public void ResolvedDateTest()
        {
            // TODO unit test for the property 'ResolvedDate'
        }
        /// <summary>
        /// Test the property 'Asset'
        /// </summary>
        [Fact]
        public void AssetTest()
        {
            // TODO unit test for the property 'Asset'
        }
        /// <summary>
        /// Test the property 'Root'
        /// </summary>
        [Fact]
        public void RootTest()
        {
            // TODO unit test for the property 'Root'
        }
        /// <summary>
        /// Test the property 'Parent'
        /// </summary>
        [Fact]
        public void ParentTest()
        {
            // TODO unit test for the property 'Parent'
        }

    }

}
