/*
 * ELEMENTS API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ElementsSDK.Api;
using ElementsSDK.Model;
using ElementsSDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ElementsSDK.Test.Model
{
    /// <summary>
    ///  Class for testing DeletedWorkspace
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DeletedWorkspaceTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DeletedWorkspace
        //private DeletedWorkspace instance;

        public DeletedWorkspaceTests()
        {
            // TODO uncomment below to create an instance of DeletedWorkspace
            //instance = new DeletedWorkspace();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DeletedWorkspace
        /// </summary>
        [Fact]
        public void DeletedWorkspaceInstanceTest()
        {
            // TODO uncomment below to test "IsType" DeletedWorkspace
            //Assert.IsType<DeletedWorkspace>(instance);
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Path'
        /// </summary>
        [Fact]
        public void PathTest()
        {
            // TODO unit test for the property 'Path'
        }

    }

}
