/*
 * ELEMENTS API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ElementsSDK.Api;
using ElementsSDK.Model;
using ElementsSDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ElementsSDK.Test.Model
{
    /// <summary>
    ///  Class for testing ElementsUserReference
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ElementsUserReferenceTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ElementsUserReference
        //private ElementsUserReference instance;

        public ElementsUserReferenceTests()
        {
            // TODO uncomment below to create an instance of ElementsUserReference
            //instance = new ElementsUserReference();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ElementsUserReference
        /// </summary>
        [Fact]
        public void ElementsUserReferenceInstanceTest()
        {
            // TODO uncomment below to test "IsType" ElementsUserReference
            //Assert.IsType<ElementsUserReference>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'AllowChangingPassword'
        /// </summary>
        [Fact]
        public void AllowChangingPasswordTest()
        {
            // TODO unit test for the property 'AllowChangingPassword'
        }
        /// <summary>
        /// Test the property 'AllowWanLogin'
        /// </summary>
        [Fact]
        public void AllowWanLoginTest()
        {
            // TODO unit test for the property 'AllowWanLogin'
        }
        /// <summary>
        /// Test the property 'AllowedFsPaths'
        /// </summary>
        [Fact]
        public void AllowedFsPathsTest()
        {
            // TODO unit test for the property 'AllowedFsPaths'
        }
        /// <summary>
        /// Test the property 'AllowedFsWritePaths'
        /// </summary>
        [Fact]
        public void AllowedFsWritePathsTest()
        {
            // TODO unit test for the property 'AllowedFsWritePaths'
        }
        /// <summary>
        /// Test the property 'Avatar'
        /// </summary>
        [Fact]
        public void AvatarTest()
        {
            // TODO unit test for the property 'Avatar'
        }
        /// <summary>
        /// Test the property 'ClientSessions'
        /// </summary>
        [Fact]
        public void ClientSessionsTest()
        {
            // TODO unit test for the property 'ClientSessions'
        }
        /// <summary>
        /// Test the property 'DefaultPage'
        /// </summary>
        [Fact]
        public void DefaultPageTest()
        {
            // TODO unit test for the property 'DefaultPage'
        }
        /// <summary>
        /// Test the property 'DisplayName'
        /// </summary>
        [Fact]
        public void DisplayNameTest()
        {
            // TODO unit test for the property 'DisplayName'
        }
        /// <summary>
        /// Test the property 'EffectivePermissions'
        /// </summary>
        [Fact]
        public void EffectivePermissionsTest()
        {
            // TODO unit test for the property 'EffectivePermissions'
        }
        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Fact]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }
        /// <summary>
        /// Test the property 'Expiry'
        /// </summary>
        [Fact]
        public void ExpiryTest()
        {
            // TODO unit test for the property 'Expiry'
        }
        /// <summary>
        /// Test the property 'AncillaryPathReadOnly'
        /// </summary>
        [Fact]
        public void AncillaryPathReadOnlyTest()
        {
            // TODO unit test for the property 'AncillaryPathReadOnly'
        }
        /// <summary>
        /// Test the property 'AncillaryPath'
        /// </summary>
        [Fact]
        public void AncillaryPathTest()
        {
            // TODO unit test for the property 'AncillaryPath'
        }
        /// <summary>
        /// Test the property 'FmBookmarks'
        /// </summary>
        [Fact]
        public void FmBookmarksTest()
        {
            // TODO unit test for the property 'FmBookmarks'
        }
        /// <summary>
        /// Test the property 'FullName'
        /// </summary>
        [Fact]
        public void FullNameTest()
        {
            // TODO unit test for the property 'FullName'
        }
        /// <summary>
        /// Test the property 'Gid'
        /// </summary>
        [Fact]
        public void GidTest()
        {
            // TODO unit test for the property 'Gid'
        }
        /// <summary>
        /// Test the property 'GroupPermissions'
        /// </summary>
        [Fact]
        public void GroupPermissionsTest()
        {
            // TODO unit test for the property 'GroupPermissions'
        }
        /// <summary>
        /// Test the property 'HasPassword'
        /// </summary>
        [Fact]
        public void HasPasswordTest()
        {
            // TODO unit test for the property 'HasPassword'
        }
        /// <summary>
        /// Test the property 'Home'
        /// </summary>
        [Fact]
        public void HomeTest()
        {
            // TODO unit test for the property 'Home'
        }
        /// <summary>
        /// Test the property 'IsExternal'
        /// </summary>
        [Fact]
        public void IsExternalTest()
        {
            // TODO unit test for the property 'IsExternal'
        }
        /// <summary>
        /// Test the property 'IsCloud'
        /// </summary>
        [Fact]
        public void IsCloudTest()
        {
            // TODO unit test for the property 'IsCloud'
        }
        /// <summary>
        /// Test the property 'IsCloudDefault'
        /// </summary>
        [Fact]
        public void IsCloudDefaultTest()
        {
            // TODO unit test for the property 'IsCloudDefault'
        }
        /// <summary>
        /// Test the property 'IsEnabled'
        /// </summary>
        [Fact]
        public void IsEnabledTest()
        {
            // TODO unit test for the property 'IsEnabled'
        }
        /// <summary>
        /// Test the property 'Language'
        /// </summary>
        [Fact]
        public void LanguageTest()
        {
            // TODO unit test for the property 'Language'
        }
        /// <summary>
        /// Test the property 'LastSeen'
        /// </summary>
        [Fact]
        public void LastSeenTest()
        {
            // TODO unit test for the property 'LastSeen'
        }
        /// <summary>
        /// Test the property 'Ldap'
        /// </summary>
        [Fact]
        public void LdapTest()
        {
            // TODO unit test for the property 'Ldap'
        }
        /// <summary>
        /// Test the property 'LdapDn'
        /// </summary>
        [Fact]
        public void LdapDnTest()
        {
            // TODO unit test for the property 'LdapDn'
        }
        /// <summary>
        /// Test the property 'PasswordChangeRequired'
        /// </summary>
        [Fact]
        public void PasswordChangeRequiredTest()
        {
            // TODO unit test for the property 'PasswordChangeRequired'
        }
        /// <summary>
        /// Test the property 'Permissions'
        /// </summary>
        [Fact]
        public void PermissionsTest()
        {
            // TODO unit test for the property 'Permissions'
        }
        /// <summary>
        /// Test the property 'ShaperCeiling'
        /// </summary>
        [Fact]
        public void ShaperCeilingTest()
        {
            // TODO unit test for the property 'ShaperCeiling'
        }
        /// <summary>
        /// Test the property 'ShaperRate'
        /// </summary>
        [Fact]
        public void ShaperRateTest()
        {
            // TODO unit test for the property 'ShaperRate'
        }
        /// <summary>
        /// Test the property 'SyncId'
        /// </summary>
        [Fact]
        public void SyncIdTest()
        {
            // TODO unit test for the property 'SyncId'
        }
        /// <summary>
        /// Test the property 'TotpEnabled'
        /// </summary>
        [Fact]
        public void TotpEnabledTest()
        {
            // TODO unit test for the property 'TotpEnabled'
        }
        /// <summary>
        /// Test the property 'Uid'
        /// </summary>
        [Fact]
        public void UidTest()
        {
            // TODO unit test for the property 'Uid'
        }
        /// <summary>
        /// Test the property 'UnixUsername'
        /// </summary>
        [Fact]
        public void UnixUsernameTest()
        {
            // TODO unit test for the property 'UnixUsername'
        }
        /// <summary>
        /// Test the property 'Username'
        /// </summary>
        [Fact]
        public void UsernameTest()
        {
            // TODO unit test for the property 'Username'
        }

    }

}
