/*
 * ELEMENTS API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ElementsSDK.Api;
using ElementsSDK.Model;
using ElementsSDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ElementsSDK.Test.Model
{
    /// <summary>
    ///  Class for testing FilesystemFile
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class FilesystemFileTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for FilesystemFile
        //private FilesystemFile instance;

        public FilesystemFileTests()
        {
            // TODO uncomment below to create an instance of FilesystemFile
            //instance = new FilesystemFile();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of FilesystemFile
        /// </summary>
        [Fact]
        public void FilesystemFileInstanceTest()
        {
            // TODO uncomment below to test "IsType" FilesystemFile
            //Assert.IsType<FilesystemFile>(instance);
        }


        /// <summary>
        /// Test the property 'Path'
        /// </summary>
        [Fact]
        public void PathTest()
        {
            // TODO unit test for the property 'Path'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Size'
        /// </summary>
        [Fact]
        public void SizeTest()
        {
            // TODO unit test for the property 'Size'
        }
        /// <summary>
        /// Test the property 'TotalSize'
        /// </summary>
        [Fact]
        public void TotalSizeTest()
        {
            // TODO unit test for the property 'TotalSize'
        }
        /// <summary>
        /// Test the property 'IsDir'
        /// </summary>
        [Fact]
        public void IsDirTest()
        {
            // TODO unit test for the property 'IsDir'
        }
        /// <summary>
        /// Test the property 'Files'
        /// </summary>
        [Fact]
        public void FilesTest()
        {
            // TODO unit test for the property 'Files'
        }
        /// <summary>
        /// Test the property 'Parent'
        /// </summary>
        [Fact]
        public void ParentTest()
        {
            // TODO unit test for the property 'Parent'
        }
        /// <summary>
        /// Test the property 'ModificationTime'
        /// </summary>
        [Fact]
        public void ModificationTimeTest()
        {
            // TODO unit test for the property 'ModificationTime'
        }
        /// <summary>
        /// Test the property 'AccessTime'
        /// </summary>
        [Fact]
        public void AccessTimeTest()
        {
            // TODO unit test for the property 'AccessTime'
        }
        /// <summary>
        /// Test the property 'CreationTime'
        /// </summary>
        [Fact]
        public void CreationTimeTest()
        {
            // TODO unit test for the property 'CreationTime'
        }
        /// <summary>
        /// Test the property 'Mode'
        /// </summary>
        [Fact]
        public void ModeTest()
        {
            // TODO unit test for the property 'Mode'
        }
        /// <summary>
        /// Test the property 'Uid'
        /// </summary>
        [Fact]
        public void UidTest()
        {
            // TODO unit test for the property 'Uid'
        }
        /// <summary>
        /// Test the property 'Gid'
        /// </summary>
        [Fact]
        public void GidTest()
        {
            // TODO unit test for the property 'Gid'
        }
        /// <summary>
        /// Test the property 'User'
        /// </summary>
        [Fact]
        public void UserTest()
        {
            // TODO unit test for the property 'User'
        }
        /// <summary>
        /// Test the property 'Group'
        /// </summary>
        [Fact]
        public void GroupTest()
        {
            // TODO unit test for the property 'Group'
        }
        /// <summary>
        /// Test the property 'Recursive'
        /// </summary>
        [Fact]
        public void RecursiveTest()
        {
            // TODO unit test for the property 'Recursive'
        }
        /// <summary>
        /// Test the property 'Affinity'
        /// </summary>
        [Fact]
        public void AffinityTest()
        {
            // TODO unit test for the property 'Affinity'
        }
        /// <summary>
        /// Test the property 'ModeSetuid'
        /// </summary>
        [Fact]
        public void ModeSetuidTest()
        {
            // TODO unit test for the property 'ModeSetuid'
        }
        /// <summary>
        /// Test the property 'ModeSetgid'
        /// </summary>
        [Fact]
        public void ModeSetgidTest()
        {
            // TODO unit test for the property 'ModeSetgid'
        }
        /// <summary>
        /// Test the property 'ModeSetvfx'
        /// </summary>
        [Fact]
        public void ModeSetvfxTest()
        {
            // TODO unit test for the property 'ModeSetvfx'
        }
        /// <summary>
        /// Test the property 'ModeUserRead'
        /// </summary>
        [Fact]
        public void ModeUserReadTest()
        {
            // TODO unit test for the property 'ModeUserRead'
        }
        /// <summary>
        /// Test the property 'ModeUserWrite'
        /// </summary>
        [Fact]
        public void ModeUserWriteTest()
        {
            // TODO unit test for the property 'ModeUserWrite'
        }
        /// <summary>
        /// Test the property 'ModeUserExecute'
        /// </summary>
        [Fact]
        public void ModeUserExecuteTest()
        {
            // TODO unit test for the property 'ModeUserExecute'
        }
        /// <summary>
        /// Test the property 'ModeGroupRead'
        /// </summary>
        [Fact]
        public void ModeGroupReadTest()
        {
            // TODO unit test for the property 'ModeGroupRead'
        }
        /// <summary>
        /// Test the property 'ModeGroupWrite'
        /// </summary>
        [Fact]
        public void ModeGroupWriteTest()
        {
            // TODO unit test for the property 'ModeGroupWrite'
        }
        /// <summary>
        /// Test the property 'ModeGroupExecute'
        /// </summary>
        [Fact]
        public void ModeGroupExecuteTest()
        {
            // TODO unit test for the property 'ModeGroupExecute'
        }
        /// <summary>
        /// Test the property 'ModeOthersRead'
        /// </summary>
        [Fact]
        public void ModeOthersReadTest()
        {
            // TODO unit test for the property 'ModeOthersRead'
        }
        /// <summary>
        /// Test the property 'ModeOthersWrite'
        /// </summary>
        [Fact]
        public void ModeOthersWriteTest()
        {
            // TODO unit test for the property 'ModeOthersWrite'
        }
        /// <summary>
        /// Test the property 'ModeOthersExecute'
        /// </summary>
        [Fact]
        public void ModeOthersExecuteTest()
        {
            // TODO unit test for the property 'ModeOthersExecute'
        }

    }

}
