/*
 * ELEMENTS API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ElementsSDK.Api;
using ElementsSDK.Model;
using ElementsSDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ElementsSDK.Test.Model
{
    /// <summary>
    ///  Class for testing MediaRootPermissionAccessOptions
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class MediaRootPermissionAccessOptionsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for MediaRootPermissionAccessOptions
        //private MediaRootPermissionAccessOptions instance;

        public MediaRootPermissionAccessOptionsTests()
        {
            // TODO uncomment below to create an instance of MediaRootPermissionAccessOptions
            //instance = new MediaRootPermissionAccessOptions();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of MediaRootPermissionAccessOptions
        /// </summary>
        [Fact]
        public void MediaRootPermissionAccessOptionsInstanceTest()
        {
            // TODO uncomment below to test "IsType" MediaRootPermissionAccessOptions
            //Assert.IsType<MediaRootPermissionAccessOptions>(instance);
        }


        /// <summary>
        /// Test the property 'ShowTags'
        /// </summary>
        [Fact]
        public void ShowTagsTest()
        {
            // TODO unit test for the property 'ShowTags'
        }
        /// <summary>
        /// Test the property 'ShowComments'
        /// </summary>
        [Fact]
        public void ShowCommentsTest()
        {
            // TODO unit test for the property 'ShowComments'
        }
        /// <summary>
        /// Test the property 'ShowLocations'
        /// </summary>
        [Fact]
        public void ShowLocationsTest()
        {
            // TODO unit test for the property 'ShowLocations'
        }
        /// <summary>
        /// Test the property 'ShowCustomFields'
        /// </summary>
        [Fact]
        public void ShowCustomFieldsTest()
        {
            // TODO unit test for the property 'ShowCustomFields'
        }
        /// <summary>
        /// Test the property 'ShowRatings'
        /// </summary>
        [Fact]
        public void ShowRatingsTest()
        {
            // TODO unit test for the property 'ShowRatings'
        }
        /// <summary>
        /// Test the property 'ShowSubclips'
        /// </summary>
        [Fact]
        public void ShowSubclipsTest()
        {
            // TODO unit test for the property 'ShowSubclips'
        }
        /// <summary>
        /// Test the property 'ShowAiMetadata'
        /// </summary>
        [Fact]
        public void ShowAiMetadataTest()
        {
            // TODO unit test for the property 'ShowAiMetadata'
        }
        /// <summary>
        /// Test the property 'ShowMarkers'
        /// </summary>
        [Fact]
        public void ShowMarkersTest()
        {
            // TODO unit test for the property 'ShowMarkers'
        }
        /// <summary>
        /// Test the property 'AllowCreate'
        /// </summary>
        [Fact]
        public void AllowCreateTest()
        {
            // TODO unit test for the property 'AllowCreate'
        }
        /// <summary>
        /// Test the property 'AllowWriteFs'
        /// </summary>
        [Fact]
        public void AllowWriteFsTest()
        {
            // TODO unit test for the property 'AllowWriteFs'
        }
        /// <summary>
        /// Test the property 'AllowWriteDb'
        /// </summary>
        [Fact]
        public void AllowWriteDbTest()
        {
            // TODO unit test for the property 'AllowWriteDb'
        }
        /// <summary>
        /// Test the property 'AllowProxyDownload'
        /// </summary>
        [Fact]
        public void AllowProxyDownloadTest()
        {
            // TODO unit test for the property 'AllowProxyDownload'
        }
        /// <summary>
        /// Test the property 'AllowOriginalDownload'
        /// </summary>
        [Fact]
        public void AllowOriginalDownloadTest()
        {
            // TODO unit test for the property 'AllowOriginalDownload'
        }
        /// <summary>
        /// Test the property 'AllowUpload'
        /// </summary>
        [Fact]
        public void AllowUploadTest()
        {
            // TODO unit test for the property 'AllowUpload'
        }
        /// <summary>
        /// Test the property 'AllowSharing'
        /// </summary>
        [Fact]
        public void AllowSharingTest()
        {
            // TODO unit test for the property 'AllowSharing'
        }
        /// <summary>
        /// Test the property 'AllowDeleteFs'
        /// </summary>
        [Fact]
        public void AllowDeleteFsTest()
        {
            // TODO unit test for the property 'AllowDeleteFs'
        }
        /// <summary>
        /// Test the property 'AllowDeleteDb'
        /// </summary>
        [Fact]
        public void AllowDeleteDbTest()
        {
            // TODO unit test for the property 'AllowDeleteDb'
        }

    }

}
