/*
 * ELEMENTS API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ElementsSDK.Api;
using ElementsSDK.Model;
using ElementsSDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ElementsSDK.Test.Model
{
    /// <summary>
    ///  Class for testing MediaFileBundleMiniReference
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class MediaFileBundleMiniReferenceTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for MediaFileBundleMiniReference
        //private MediaFileBundleMiniReference instance;

        public MediaFileBundleMiniReferenceTests()
        {
            // TODO uncomment below to create an instance of MediaFileBundleMiniReference
            //instance = new MediaFileBundleMiniReference();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of MediaFileBundleMiniReference
        /// </summary>
        [Fact]
        public void MediaFileBundleMiniReferenceInstanceTest()
        {
            // TODO uncomment below to test "IsType" MediaFileBundleMiniReference
            //Assert.IsType<MediaFileBundleMiniReference>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Asset'
        /// </summary>
        [Fact]
        public void AssetTest()
        {
            // TODO unit test for the property 'Asset'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Location'
        /// </summary>
        [Fact]
        public void LocationTest()
        {
            // TODO unit test for the property 'Location'
        }
        /// <summary>
        /// Test the property 'Mainfile'
        /// </summary>
        [Fact]
        public void MainfileTest()
        {
            // TODO unit test for the property 'Mainfile'
        }

    }

}
