/*
 * ELEMENTS API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ElementsSDK.Api;
using ElementsSDK.Model;
using ElementsSDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ElementsSDK.Test.Model
{
    /// <summary>
    ///  Class for testing MoveWorkspaceRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class MoveWorkspaceRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for MoveWorkspaceRequest
        //private MoveWorkspaceRequest instance;

        public MoveWorkspaceRequestTests()
        {
            // TODO uncomment below to create an instance of MoveWorkspaceRequest
            //instance = new MoveWorkspaceRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of MoveWorkspaceRequest
        /// </summary>
        [Fact]
        public void MoveWorkspaceRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" MoveWorkspaceRequest
            //Assert.IsType<MoveWorkspaceRequest>(instance);
        }


        /// <summary>
        /// Test the property 'Production'
        /// </summary>
        [Fact]
        public void ProductionTest()
        {
            // TODO unit test for the property 'Production'
        }
        /// <summary>
        /// Test the property 'Volume'
        /// </summary>
        [Fact]
        public void VolumeTest()
        {
            // TODO unit test for the property 'Volume'
        }
        /// <summary>
        /// Test the property 'Directory'
        /// </summary>
        [Fact]
        public void DirectoryTest()
        {
            // TODO unit test for the property 'Directory'
        }

    }

}
