/*
 * ELEMENTS API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ElementsSDK.Api;
using ElementsSDK.Model;
using ElementsSDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ElementsSDK.Test.Model
{
    /// <summary>
    ///  Class for testing ProductionReference
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ProductionReferenceTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ProductionReference
        //private ProductionReference instance;

        public ProductionReferenceTests()
        {
            // TODO uncomment below to create an instance of ProductionReference
            //instance = new ProductionReference();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ProductionReference
        /// </summary>
        [Fact]
        public void ProductionReferenceInstanceTest()
        {
            // TODO uncomment below to test "IsType" ProductionReference
            //Assert.IsType<ProductionReference>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'IsSpecial'
        /// </summary>
        [Fact]
        public void IsSpecialTest()
        {
            // TODO unit test for the property 'IsSpecial'
        }
        /// <summary>
        /// Test the property 'SpecialType'
        /// </summary>
        [Fact]
        public void SpecialTypeTest()
        {
            // TODO unit test for the property 'SpecialType'
        }
        /// <summary>
        /// Test the property 'TotalSize'
        /// </summary>
        [Fact]
        public void TotalSizeTest()
        {
            // TODO unit test for the property 'TotalSize'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'ObscureName'
        /// </summary>
        [Fact]
        public void ObscureNameTest()
        {
            // TODO unit test for the property 'ObscureName'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'LongDescription'
        /// </summary>
        [Fact]
        public void LongDescriptionTest()
        {
            // TODO unit test for the property 'LongDescription'
        }
        /// <summary>
        /// Test the property 'Active'
        /// </summary>
        [Fact]
        public void ActiveTest()
        {
            // TODO unit test for the property 'Active'
        }
        /// <summary>
        /// Test the property 'Template'
        /// </summary>
        [Fact]
        public void TemplateTest()
        {
            // TODO unit test for the property 'Template'
        }
        /// <summary>
        /// Test the property 'DefaultGroup'
        /// </summary>
        [Fact]
        public void DefaultGroupTest()
        {
            // TODO unit test for the property 'DefaultGroup'
        }

    }

}
