/*
 * ELEMENTS API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ElementsSDK.Api;
using ElementsSDK.Model;
using ElementsSDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ElementsSDK.Test.Model
{
    /// <summary>
    ///  Class for testing ProxyCount
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ProxyCountTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ProxyCount
        //private ProxyCount instance;

        public ProxyCountTests()
        {
            // TODO uncomment below to create an instance of ProxyCount
            //instance = new ProxyCount();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ProxyCount
        /// </summary>
        [Fact]
        public void ProxyCountInstanceTest()
        {
            // TODO uncomment below to test "IsType" ProxyCount
            //Assert.IsType<ProxyCount>(instance);
        }


        /// <summary>
        /// Test the property 'Count'
        /// </summary>
        [Fact]
        public void CountTest()
        {
            // TODO unit test for the property 'Count'
        }

    }

}
