/*
 * ELEMENTS API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ElementsSDK.Api;
using ElementsSDK.Model;
using ElementsSDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ElementsSDK.Test.Model
{
    /// <summary>
    ///  Class for testing Quota
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class QuotaTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Quota
        //private Quota instance;

        public QuotaTests()
        {
            // TODO uncomment below to create an instance of Quota
            //instance = new Quota();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Quota
        /// </summary>
        [Fact]
        public void QuotaInstanceTest()
        {
            // TODO uncomment below to test "IsType" Quota
            //Assert.IsType<Quota>(instance);
        }


        /// <summary>
        /// Test the property 'Current'
        /// </summary>
        [Fact]
        public void CurrentTest()
        {
            // TODO unit test for the property 'Current'
        }
        /// <summary>
        /// Test the property 'Soft'
        /// </summary>
        [Fact]
        public void SoftTest()
        {
            // TODO unit test for the property 'Soft'
        }
        /// <summary>
        /// Test the property 'Hard'
        /// </summary>
        [Fact]
        public void HardTest()
        {
            // TODO unit test for the property 'Hard'
        }

    }

}
