/*
 * ELEMENTS API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ElementsSDK.Api;
using ElementsSDK.Model;
using ElementsSDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ElementsSDK.Test.Model
{
    /// <summary>
    ///  Class for testing RDCHost
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RDCHostTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RDCHost
        //private RDCHost instance;

        public RDCHostTests()
        {
            // TODO uncomment below to create an instance of RDCHost
            //instance = new RDCHost();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RDCHost
        /// </summary>
        [Fact]
        public void RDCHostInstanceTest()
        {
            // TODO uncomment below to test "IsType" RDCHost
            //Assert.IsType<RDCHost>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Workstation'
        /// </summary>
        [Fact]
        public void WorkstationTest()
        {
            // TODO unit test for the property 'Workstation'
        }
        /// <summary>
        /// Test the property 'Occupied'
        /// </summary>
        [Fact]
        public void OccupiedTest()
        {
            // TODO unit test for the property 'Occupied'
        }
        /// <summary>
        /// Test the property 'LastUpdated'
        /// </summary>
        [Fact]
        public void LastUpdatedTest()
        {
            // TODO unit test for the property 'LastUpdated'
        }

    }

}
