/*
 * ELEMENTS API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ElementsSDK.Api;
using ElementsSDK.Model;
using ElementsSDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ElementsSDK.Test.Model
{
    /// <summary>
    ///  Class for testing SchedulePartialUpdate
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SchedulePartialUpdateTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SchedulePartialUpdate
        //private SchedulePartialUpdate instance;

        public SchedulePartialUpdateTests()
        {
            // TODO uncomment below to create an instance of SchedulePartialUpdate
            //instance = new SchedulePartialUpdate();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SchedulePartialUpdate
        /// </summary>
        [Fact]
        public void SchedulePartialUpdateInstanceTest()
        {
            // TODO uncomment below to test "IsType" SchedulePartialUpdate
            //Assert.IsType<SchedulePartialUpdate>(instance);
        }


        /// <summary>
        /// Test the property 'Variables'
        /// </summary>
        [Fact]
        public void VariablesTest()
        {
            // TODO unit test for the property 'Variables'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'Enabled'
        /// </summary>
        [Fact]
        public void EnabledTest()
        {
            // TODO unit test for the property 'Enabled'
        }
        /// <summary>
        /// Test the property 'LastRun'
        /// </summary>
        [Fact]
        public void LastRunTest()
        {
            // TODO unit test for the property 'LastRun'
        }
        /// <summary>
        /// Test the property 'Every'
        /// </summary>
        [Fact]
        public void EveryTest()
        {
            // TODO unit test for the property 'Every'
        }
        /// <summary>
        /// Test the property 'Period'
        /// </summary>
        [Fact]
        public void PeriodTest()
        {
            // TODO unit test for the property 'Period'
        }
        /// <summary>
        /// Test the property 'CrontabDayOfMonth'
        /// </summary>
        [Fact]
        public void CrontabDayOfMonthTest()
        {
            // TODO unit test for the property 'CrontabDayOfMonth'
        }
        /// <summary>
        /// Test the property 'CrontabDayOfWeek'
        /// </summary>
        [Fact]
        public void CrontabDayOfWeekTest()
        {
            // TODO unit test for the property 'CrontabDayOfWeek'
        }
        /// <summary>
        /// Test the property 'CrontabHour'
        /// </summary>
        [Fact]
        public void CrontabHourTest()
        {
            // TODO unit test for the property 'CrontabHour'
        }
        /// <summary>
        /// Test the property 'CrontabMinute'
        /// </summary>
        [Fact]
        public void CrontabMinuteTest()
        {
            // TODO unit test for the property 'CrontabMinute'
        }
        /// <summary>
        /// Test the property 'CrontabMonthOfYear'
        /// </summary>
        [Fact]
        public void CrontabMonthOfYearTest()
        {
            // TODO unit test for the property 'CrontabMonthOfYear'
        }
        /// <summary>
        /// Test the property 'Job'
        /// </summary>
        [Fact]
        public void JobTest()
        {
            // TODO unit test for the property 'Job'
        }

    }

}
