/*
 * ELEMENTS API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ElementsSDK.Api;
using ElementsSDK.Model;
using ElementsSDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ElementsSDK.Test.Model
{
    /// <summary>
    ///  Class for testing SearchEndpointResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SearchEndpointResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SearchEndpointResponse
        //private SearchEndpointResponse instance;

        public SearchEndpointResponseTests()
        {
            // TODO uncomment below to create an instance of SearchEndpointResponse
            //instance = new SearchEndpointResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SearchEndpointResponse
        /// </summary>
        [Fact]
        public void SearchEndpointResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" SearchEndpointResponse
            //Assert.IsType<SearchEndpointResponse>(instance);
        }


        /// <summary>
        /// Test the property 'Tapes'
        /// </summary>
        [Fact]
        public void TapesTest()
        {
            // TODO unit test for the property 'Tapes'
        }
        /// <summary>
        /// Test the property 'Entries'
        /// </summary>
        [Fact]
        public void EntriesTest()
        {
            // TODO unit test for the property 'Entries'
        }
        /// <summary>
        /// Test the property 'Total'
        /// </summary>
        [Fact]
        public void TotalTest()
        {
            // TODO unit test for the property 'Total'
        }

    }

}
