/*
 * ELEMENTS API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ElementsSDK.Api;
using ElementsSDK.Model;
using ElementsSDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ElementsSDK.Test.Model
{
    /// <summary>
    ///  Class for testing SharePartialUpdate
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SharePartialUpdateTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SharePartialUpdate
        //private SharePartialUpdate instance;

        public SharePartialUpdateTests()
        {
            // TODO uncomment below to create an instance of SharePartialUpdate
            //instance = new SharePartialUpdate();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SharePartialUpdate
        /// </summary>
        [Fact]
        public void SharePartialUpdateInstanceTest()
        {
            // TODO uncomment below to test "IsType" SharePartialUpdate
            //Assert.IsType<SharePartialUpdate>(instance);
        }


        /// <summary>
        /// Test the property 'SharingNfsPermissions'
        /// </summary>
        [Fact]
        public void SharingNfsPermissionsTest()
        {
            // TODO unit test for the property 'SharingNfsPermissions'
        }
        /// <summary>
        /// Test the property 'Volume'
        /// </summary>
        [Fact]
        public void VolumeTest()
        {
            // TODO unit test for the property 'Volume'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Path'
        /// </summary>
        [Fact]
        public void PathTest()
        {
            // TODO unit test for the property 'Path'
        }
        /// <summary>
        /// Test the property 'ShareSmb'
        /// </summary>
        [Fact]
        public void ShareSmbTest()
        {
            // TODO unit test for the property 'ShareSmb'
        }
        /// <summary>
        /// Test the property 'ShareNfs'
        /// </summary>
        [Fact]
        public void ShareNfsTest()
        {
            // TODO unit test for the property 'ShareNfs'
        }
        /// <summary>
        /// Test the property 'ShareAfp'
        /// </summary>
        [Fact]
        public void ShareAfpTest()
        {
            // TODO unit test for the property 'ShareAfp'
        }
        /// <summary>
        /// Test the property 'SharingReadOnly'
        /// </summary>
        [Fact]
        public void SharingReadOnlyTest()
        {
            // TODO unit test for the property 'SharingReadOnly'
        }
        /// <summary>
        /// Test the property 'SharingHidden'
        /// </summary>
        [Fact]
        public void SharingHiddenTest()
        {
            // TODO unit test for the property 'SharingHidden'
        }
        /// <summary>
        /// Test the property 'SharingRequireLogin'
        /// </summary>
        [Fact]
        public void SharingRequireLoginTest()
        {
            // TODO unit test for the property 'SharingRequireLogin'
        }
        /// <summary>
        /// Test the property 'SmbExtraConfig'
        /// </summary>
        [Fact]
        public void SmbExtraConfigTest()
        {
            // TODO unit test for the property 'SmbExtraConfig'
        }
        /// <summary>
        /// Test the property 'AfpExtraConfig'
        /// </summary>
        [Fact]
        public void AfpExtraConfigTest()
        {
            // TODO unit test for the property 'AfpExtraConfig'
        }
        /// <summary>
        /// Test the property 'RwAccessGroup'
        /// </summary>
        [Fact]
        public void RwAccessGroupTest()
        {
            // TODO unit test for the property 'RwAccessGroup'
        }
        /// <summary>
        /// Test the property 'RoAccessGroup'
        /// </summary>
        [Fact]
        public void RoAccessGroupTest()
        {
            // TODO unit test for the property 'RoAccessGroup'
        }

    }

}
