/*
 * ELEMENTS API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ElementsSDK.Api;
using ElementsSDK.Model;
using ElementsSDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ElementsSDK.Test.Model
{
    /// <summary>
    ///  Class for testing StornextManagerAttributes
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class StornextManagerAttributesTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for StornextManagerAttributes
        //private StornextManagerAttributes instance;

        public StornextManagerAttributesTests()
        {
            // TODO uncomment below to create an instance of StornextManagerAttributes
            //instance = new StornextManagerAttributes();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of StornextManagerAttributes
        /// </summary>
        [Fact]
        public void StornextManagerAttributesInstanceTest()
        {
            // TODO uncomment below to test "IsType" StornextManagerAttributes
            //Assert.IsType<StornextManagerAttributes>(instance);
        }


        /// <summary>
        /// Test the property 'Location'
        /// </summary>
        [Fact]
        public void LocationTest()
        {
            // TODO unit test for the property 'Location'
        }
        /// <summary>
        /// Test the property 'PolicyClass'
        /// </summary>
        [Fact]
        public void PolicyClassTest()
        {
            // TODO unit test for the property 'PolicyClass'
        }
        /// <summary>
        /// Test the property 'ExistingCopies'
        /// </summary>
        [Fact]
        public void ExistingCopiesTest()
        {
            // TODO unit test for the property 'ExistingCopies'
        }
        /// <summary>
        /// Test the property 'TargetCopies'
        /// </summary>
        [Fact]
        public void TargetCopiesTest()
        {
            // TODO unit test for the property 'TargetCopies'
        }

    }

}
