/*
 * ELEMENTS API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ElementsSDK.Api;
using ElementsSDK.Model;
using ElementsSDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ElementsSDK.Test.Model
{
    /// <summary>
    ///  Class for testing SubtaskReference
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SubtaskReferenceTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SubtaskReference
        //private SubtaskReference instance;

        public SubtaskReferenceTests()
        {
            // TODO uncomment below to create an instance of SubtaskReference
            //instance = new SubtaskReference();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SubtaskReference
        /// </summary>
        [Fact]
        public void SubtaskReferenceInstanceTest()
        {
            // TODO uncomment below to test "IsType" SubtaskReference
            //Assert.IsType<SubtaskReference>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Kwargs'
        /// </summary>
        [Fact]
        public void KwargsTest()
        {
            // TODO unit test for the property 'Kwargs'
        }
        /// <summary>
        /// Test the property 'GraphLayout'
        /// </summary>
        [Fact]
        public void GraphLayoutTest()
        {
            // TODO unit test for the property 'GraphLayout'
        }
        /// <summary>
        /// Test the property 'ValidationError'
        /// </summary>
        [Fact]
        public void ValidationErrorTest()
        {
            // TODO unit test for the property 'ValidationError'
        }
        /// <summary>
        /// Test the property 'Trigger'
        /// </summary>
        [Fact]
        public void TriggerTest()
        {
            // TODO unit test for the property 'Trigger'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'NoopDontSave'
        /// </summary>
        [Fact]
        public void NoopDontSaveTest()
        {
            // TODO unit test for the property 'NoopDontSave'
        }
        /// <summary>
        /// Test the property 'NoConcurrency'
        /// </summary>
        [Fact]
        public void NoConcurrencyTest()
        {
            // TODO unit test for the property 'NoConcurrency'
        }
        /// <summary>
        /// Test the property 'Timeout'
        /// </summary>
        [Fact]
        public void TimeoutTest()
        {
            // TODO unit test for the property 'Timeout'
        }
        /// <summary>
        /// Test the property 'LogVariable'
        /// </summary>
        [Fact]
        public void LogVariableTest()
        {
            // TODO unit test for the property 'LogVariable'
        }
        /// <summary>
        /// Test the property 'Task'
        /// </summary>
        [Fact]
        public void TaskTest()
        {
            // TODO unit test for the property 'Task'
        }
        /// <summary>
        /// Test the property 'ConditionVariable'
        /// </summary>
        [Fact]
        public void ConditionVariableTest()
        {
            // TODO unit test for the property 'ConditionVariable'
        }
        /// <summary>
        /// Test the property 'ConditionValue'
        /// </summary>
        [Fact]
        public void ConditionValueTest()
        {
            // TODO unit test for the property 'ConditionValue'
        }
        /// <summary>
        /// Test the property 'Sync'
        /// </summary>
        [Fact]
        public void SyncTest()
        {
            // TODO unit test for the property 'Sync'
        }
        /// <summary>
        /// Test the property 'Queue'
        /// </summary>
        [Fact]
        public void QueueTest()
        {
            // TODO unit test for the property 'Queue'
        }
        /// <summary>
        /// Test the property 'EnqueueAtFront'
        /// </summary>
        [Fact]
        public void EnqueueAtFrontTest()
        {
            // TODO unit test for the property 'EnqueueAtFront'
        }
        /// <summary>
        /// Test the property 'Parent'
        /// </summary>
        [Fact]
        public void ParentTest()
        {
            // TODO unit test for the property 'Parent'
        }
        /// <summary>
        /// Test the property 'RelativeTo'
        /// </summary>
        [Fact]
        public void RelativeToTest()
        {
            // TODO unit test for the property 'RelativeTo'
        }

    }

}
