/*
 * ELEMENTS API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ElementsSDK.Api;
using ElementsSDK.Model;
using ElementsSDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ElementsSDK.Test.Model
{
    /// <summary>
    ///  Class for testing SystemInfoEndpointResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SystemInfoEndpointResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SystemInfoEndpointResponse
        //private SystemInfoEndpointResponse instance;

        public SystemInfoEndpointResponseTests()
        {
            // TODO uncomment below to create an instance of SystemInfoEndpointResponse
            //instance = new SystemInfoEndpointResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SystemInfoEndpointResponse
        /// </summary>
        [Fact]
        public void SystemInfoEndpointResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" SystemInfoEndpointResponse
            //Assert.IsType<SystemInfoEndpointResponse>(instance);
        }


        /// <summary>
        /// Test the property 'License'
        /// </summary>
        [Fact]
        public void LicenseTest()
        {
            // TODO unit test for the property 'License'
        }
        /// <summary>
        /// Test the property 'ClientApiVersion'
        /// </summary>
        [Fact]
        public void ClientApiVersionTest()
        {
            // TODO unit test for the property 'ClientApiVersion'
        }
        /// <summary>
        /// Test the property 'NtHostname'
        /// </summary>
        [Fact]
        public void NtHostnameTest()
        {
            // TODO unit test for the property 'NtHostname'
        }
        /// <summary>
        /// Test the property 'OffersNtpSync'
        /// </summary>
        [Fact]
        public void OffersNtpSyncTest()
        {
            // TODO unit test for the property 'OffersNtpSync'
        }
        /// <summary>
        /// Test the property 'Language'
        /// </summary>
        [Fact]
        public void LanguageTest()
        {
            // TODO unit test for the property 'Language'
        }
        /// <summary>
        /// Test the property 'SamlProviders'
        /// </summary>
        [Fact]
        public void SamlProvidersTest()
        {
            // TODO unit test for the property 'SamlProviders'
        }
        /// <summary>
        /// Test the property 'Version'
        /// </summary>
        [Fact]
        public void VersionTest()
        {
            // TODO unit test for the property 'Version'
        }
        /// <summary>
        /// Test the property 'GlobalAlerts'
        /// </summary>
        [Fact]
        public void GlobalAlertsTest()
        {
            // TODO unit test for the property 'GlobalAlerts'
        }

    }

}
