/*
 * ELEMENTS API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ElementsSDK.Api;
using ElementsSDK.Model;
using ElementsSDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ElementsSDK.Test.Model
{
    /// <summary>
    ///  Class for testing TapePartialUpdate
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TapePartialUpdateTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TapePartialUpdate
        //private TapePartialUpdate instance;

        public TapePartialUpdateTests()
        {
            // TODO uncomment below to create an instance of TapePartialUpdate
            //instance = new TapePartialUpdate();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TapePartialUpdate
        /// </summary>
        [Fact]
        public void TapePartialUpdateInstanceTest()
        {
            // TODO uncomment below to test "IsType" TapePartialUpdate
            //Assert.IsType<TapePartialUpdate>(instance);
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Uuid'
        /// </summary>
        [Fact]
        public void UuidTest()
        {
            // TODO unit test for the property 'Uuid'
        }
        /// <summary>
        /// Test the property 'Generation'
        /// </summary>
        [Fact]
        public void GenerationTest()
        {
            // TODO unit test for the property 'Generation'
        }
        /// <summary>
        /// Test the property 'CustomA'
        /// </summary>
        [Fact]
        public void CustomATest()
        {
            // TODO unit test for the property 'CustomA'
        }
        /// <summary>
        /// Test the property 'CustomB'
        /// </summary>
        [Fact]
        public void CustomBTest()
        {
            // TODO unit test for the property 'CustomB'
        }
        /// <summary>
        /// Test the property 'CustomC'
        /// </summary>
        [Fact]
        public void CustomCTest()
        {
            // TODO unit test for the property 'CustomC'
        }
        /// <summary>
        /// Test the property 'CustomD'
        /// </summary>
        [Fact]
        public void CustomDTest()
        {
            // TODO unit test for the property 'CustomD'
        }
        /// <summary>
        /// Test the property 'FreeSpace'
        /// </summary>
        [Fact]
        public void FreeSpaceTest()
        {
            // TODO unit test for the property 'FreeSpace'
        }
        /// <summary>
        /// Test the property 'LoadCounter'
        /// </summary>
        [Fact]
        public void LoadCounterTest()
        {
            // TODO unit test for the property 'LoadCounter'
        }
        /// <summary>
        /// Test the property 'ErrorCounter'
        /// </summary>
        [Fact]
        public void ErrorCounterTest()
        {
            // TODO unit test for the property 'ErrorCounter'
        }
        /// <summary>
        /// Test the property 'ErrorReason'
        /// </summary>
        [Fact]
        public void ErrorReasonTest()
        {
            // TODO unit test for the property 'ErrorReason'
        }
        /// <summary>
        /// Test the property 'Active'
        /// </summary>
        [Fact]
        public void ActiveTest()
        {
            // TODO unit test for the property 'Active'
        }
        /// <summary>
        /// Test the property 'Lto'
        /// </summary>
        [Fact]
        public void LtoTest()
        {
            // TODO unit test for the property 'Lto'
        }
        /// <summary>
        /// Test the property 'Group'
        /// </summary>
        [Fact]
        public void GroupTest()
        {
            // TODO unit test for the property 'Group'
        }

    }

}
