/*
 * ELEMENTS API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ElementsSDK.Api;
using ElementsSDK.Model;
using ElementsSDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ElementsSDK.Test.Model
{
    /// <summary>
    ///  Class for testing TapeJob
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TapeJobTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TapeJob
        //private TapeJob instance;

        public TapeJobTests()
        {
            // TODO uncomment below to create an instance of TapeJob
            //instance = new TapeJob();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TapeJob
        /// </summary>
        [Fact]
        public void TapeJobInstanceTest()
        {
            // TODO uncomment below to test "IsType" TapeJob
            //Assert.IsType<TapeJob>(instance);
        }


        /// <summary>
        /// Test the property 'Group'
        /// </summary>
        [Fact]
        public void GroupTest()
        {
            // TODO unit test for the property 'Group'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Exclude'
        /// </summary>
        [Fact]
        public void ExcludeTest()
        {
            // TODO unit test for the property 'Exclude'
        }
        /// <summary>
        /// Test the property 'SelectedTape'
        /// </summary>
        [Fact]
        public void SelectedTapeTest()
        {
            // TODO unit test for the property 'SelectedTape'
        }
        /// <summary>
        /// Test the property 'HasCopy2'
        /// </summary>
        [Fact]
        public void HasCopy2Test()
        {
            // TODO unit test for the property 'HasCopy2'
        }
        /// <summary>
        /// Test the property 'Copy2Id'
        /// </summary>
        [Fact]
        public void Copy2IdTest()
        {
            // TODO unit test for the property 'Copy2Id'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'Copied'
        /// </summary>
        [Fact]
        public void CopiedTest()
        {
            // TODO unit test for the property 'Copied'
        }
        /// <summary>
        /// Test the property 'Total'
        /// </summary>
        [Fact]
        public void TotalTest()
        {
            // TODO unit test for the property 'Total'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'Export'
        /// </summary>
        [Fact]
        public void ExportTest()
        {
            // TODO unit test for the property 'Export'
        }
        /// <summary>
        /// Test the property 'Start'
        /// </summary>
        [Fact]
        public void StartTest()
        {
            // TODO unit test for the property 'Start'
        }
        /// <summary>
        /// Test the property 'Duration'
        /// </summary>
        [Fact]
        public void DurationTest()
        {
            // TODO unit test for the property 'Duration'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Destination'
        /// </summary>
        [Fact]
        public void DestinationTest()
        {
            // TODO unit test for the property 'Destination'
        }
        /// <summary>
        /// Test the property 'DeleteSource'
        /// </summary>
        [Fact]
        public void DeleteSourceTest()
        {
            // TODO unit test for the property 'DeleteSource'
        }
        /// <summary>
        /// Test the property 'Destination2'
        /// </summary>
        [Fact]
        public void Destination2Test()
        {
            // TODO unit test for the property 'Destination2'
        }
        /// <summary>
        /// Test the property 'Group2'
        /// </summary>
        [Fact]
        public void Group2Test()
        {
            // TODO unit test for the property 'Group2'
        }
        /// <summary>
        /// Test the property 'Export2'
        /// </summary>
        [Fact]
        public void Export2Test()
        {
            // TODO unit test for the property 'Export2'
        }
        /// <summary>
        /// Test the property 'Md5'
        /// </summary>
        [Fact]
        public void Md5Test()
        {
            // TODO unit test for the property 'Md5'
        }
        /// <summary>
        /// Test the property 'StartDate'
        /// </summary>
        [Fact]
        public void StartDateTest()
        {
            // TODO unit test for the property 'StartDate'
        }
        /// <summary>
        /// Test the property 'LogPath'
        /// </summary>
        [Fact]
        public void LogPathTest()
        {
            // TODO unit test for the property 'LogPath'
        }
        /// <summary>
        /// Test the property 'LogExists'
        /// </summary>
        [Fact]
        public void LogExistsTest()
        {
            // TODO unit test for the property 'LogExists'
        }

    }

}
