/*
 * ELEMENTS API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ElementsSDK.Api;
using ElementsSDK.Model;
using ElementsSDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ElementsSDK.Test.Model
{
    /// <summary>
    ///  Class for testing TeamsConnectionPartialUpdate
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TeamsConnectionPartialUpdateTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TeamsConnectionPartialUpdate
        //private TeamsConnectionPartialUpdate instance;

        public TeamsConnectionPartialUpdateTests()
        {
            // TODO uncomment below to create an instance of TeamsConnectionPartialUpdate
            //instance = new TeamsConnectionPartialUpdate();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TeamsConnectionPartialUpdate
        /// </summary>
        [Fact]
        public void TeamsConnectionPartialUpdateInstanceTest()
        {
            // TODO uncomment below to test "IsType" TeamsConnectionPartialUpdate
            //Assert.IsType<TeamsConnectionPartialUpdate>(instance);
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

    }

}
