/*
 * ELEMENTS API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ElementsSDK.Api;
using ElementsSDK.Model;
using ElementsSDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ElementsSDK.Test.Model
{
    /// <summary>
    ///  Class for testing TimelineExportRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TimelineExportRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TimelineExportRequest
        //private TimelineExportRequest instance;

        public TimelineExportRequestTests()
        {
            // TODO uncomment below to create an instance of TimelineExportRequest
            //instance = new TimelineExportRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TimelineExportRequest
        /// </summary>
        [Fact]
        public void TimelineExportRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" TimelineExportRequest
            //Assert.IsType<TimelineExportRequest>(instance);
        }


        /// <summary>
        /// Test the property 'Project'
        /// </summary>
        [Fact]
        public void ProjectTest()
        {
            // TODO unit test for the property 'Project'
        }
        /// <summary>
        /// Test the property 'Sequence'
        /// </summary>
        [Fact]
        public void SequenceTest()
        {
            // TODO unit test for the property 'Sequence'
        }
        /// <summary>
        /// Test the property 'Format'
        /// </summary>
        [Fact]
        public void FormatTest()
        {
            // TODO unit test for the property 'Format'
        }

    }

}
