/*
 * ELEMENTS API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ElementsSDK.Api;
using ElementsSDK.Model;
using ElementsSDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ElementsSDK.Test.Model
{
    /// <summary>
    ///  Class for testing TimeEndpointRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TimeEndpointRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TimeEndpointRequest
        //private TimeEndpointRequest instance;

        public TimeEndpointRequestTests()
        {
            // TODO uncomment below to create an instance of TimeEndpointRequest
            //instance = new TimeEndpointRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TimeEndpointRequest
        /// </summary>
        [Fact]
        public void TimeEndpointRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" TimeEndpointRequest
            //Assert.IsType<TimeEndpointRequest>(instance);
        }


        /// <summary>
        /// Test the property 'Time'
        /// </summary>
        [Fact]
        public void TimeTest()
        {
            // TODO unit test for the property 'Time'
        }
        /// <summary>
        /// Test the property 'Timezone'
        /// </summary>
        [Fact]
        public void TimezoneTest()
        {
            // TODO unit test for the property 'Timezone'
        }

    }

}
