/*
 * ELEMENTS API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ElementsSDK.Api;
using ElementsSDK.Model;
using ElementsSDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ElementsSDK.Test.Model
{
    /// <summary>
    ///  Class for testing TranscoderProfile
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TranscoderProfileTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TranscoderProfile
        //private TranscoderProfile instance;

        public TranscoderProfileTests()
        {
            // TODO uncomment below to create an instance of TranscoderProfile
            //instance = new TranscoderProfile();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TranscoderProfile
        /// </summary>
        [Fact]
        public void TranscoderProfileInstanceTest()
        {
            // TODO uncomment below to test "IsType" TranscoderProfile
            //Assert.IsType<TranscoderProfile>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Options'
        /// </summary>
        [Fact]
        public void OptionsTest()
        {
            // TODO unit test for the property 'Options'
        }
        /// <summary>
        /// Test the property 'Binary'
        /// </summary>
        [Fact]
        public void BinaryTest()
        {
            // TODO unit test for the property 'Binary'
        }
        /// <summary>
        /// Test the property 'Command'
        /// </summary>
        [Fact]
        public void CommandTest()
        {
            // TODO unit test for the property 'Command'
        }
        /// <summary>
        /// Test the property 'OutputExtension'
        /// </summary>
        [Fact]
        public void OutputExtensionTest()
        {
            // TODO unit test for the property 'OutputExtension'
        }
        /// <summary>
        /// Test the property 'AcceptsBitrate'
        /// </summary>
        [Fact]
        public void AcceptsBitrateTest()
        {
            // TODO unit test for the property 'AcceptsBitrate'
        }
        /// <summary>
        /// Test the property 'AcceptsFps'
        /// </summary>
        [Fact]
        public void AcceptsFpsTest()
        {
            // TODO unit test for the property 'AcceptsFps'
        }
        /// <summary>
        /// Test the property 'AcceptsResolution'
        /// </summary>
        [Fact]
        public void AcceptsResolutionTest()
        {
            // TODO unit test for the property 'AcceptsResolution'
        }

    }

}
