/*
 * ELEMENTS API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ElementsSDK.Api;
using ElementsSDK.Model;
using ElementsSDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ElementsSDK.Test.Model
{
    /// <summary>
    ///  Class for testing VolumeStats
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class VolumeStatsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for VolumeStats
        //private VolumeStats instance;

        public VolumeStatsTests()
        {
            // TODO uncomment below to create an instance of VolumeStats
            //instance = new VolumeStats();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of VolumeStats
        /// </summary>
        [Fact]
        public void VolumeStatsInstanceTest()
        {
            // TODO uncomment below to test "IsType" VolumeStats
            //Assert.IsType<VolumeStats>(instance);
        }


        /// <summary>
        /// Test the property 'Usage'
        /// </summary>
        [Fact]
        public void UsageTest()
        {
            // TODO unit test for the property 'Usage'
        }

    }

}
