/*
 * ELEMENTS API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ElementsSDK.Api;
using ElementsSDK.Model;
using ElementsSDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ElementsSDK.Test.Model
{
    /// <summary>
    ///  Class for testing Workspace
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class WorkspaceTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Workspace
        //private Workspace instance;

        public WorkspaceTests()
        {
            // TODO uncomment below to create an instance of Workspace
            //instance = new Workspace();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Workspace
        /// </summary>
        [Fact]
        public void WorkspaceInstanceTest()
        {
            // TODO uncomment below to test "IsType" Workspace
            //Assert.IsType<Workspace>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Production'
        /// </summary>
        [Fact]
        public void ProductionTest()
        {
            // TODO unit test for the property 'Production'
        }
        /// <summary>
        /// Test the property 'Volume'
        /// </summary>
        [Fact]
        public void VolumeTest()
        {
            // TODO unit test for the property 'Volume'
        }
        /// <summary>
        /// Test the property 'VolumePath'
        /// </summary>
        [Fact]
        public void VolumePathTest()
        {
            // TODO unit test for the property 'VolumePath'
        }
        /// <summary>
        /// Test the property 'Path'
        /// </summary>
        [Fact]
        public void PathTest()
        {
            // TODO unit test for the property 'Path'
        }
        /// <summary>
        /// Test the property 'SharingNfsPermissions'
        /// </summary>
        [Fact]
        public void SharingNfsPermissionsTest()
        {
            // TODO unit test for the property 'SharingNfsPermissions'
        }
        /// <summary>
        /// Test the property 'FullPath'
        /// </summary>
        [Fact]
        public void FullPathTest()
        {
            // TODO unit test for the property 'FullPath'
        }
        /// <summary>
        /// Test the property 'CurrentShareName'
        /// </summary>
        [Fact]
        public void CurrentShareNameTest()
        {
            // TODO unit test for the property 'CurrentShareName'
        }
        /// <summary>
        /// Test the property 'Endpoints'
        /// </summary>
        [Fact]
        public void EndpointsTest()
        {
            // TODO unit test for the property 'Endpoints'
        }
        /// <summary>
        /// Test the property 'Quota'
        /// </summary>
        [Fact]
        public void QuotaTest()
        {
            // TODO unit test for the property 'Quota'
        }
        /// <summary>
        /// Test the property 'SizeUsed'
        /// </summary>
        [Fact]
        public void SizeUsedTest()
        {
            // TODO unit test for the property 'SizeUsed'
        }
        /// <summary>
        /// Test the property 'SizeTotal'
        /// </summary>
        [Fact]
        public void SizeTotalTest()
        {
            // TODO unit test for the property 'SizeTotal'
        }
        /// <summary>
        /// Test the property 'Bookmarked'
        /// </summary>
        [Fact]
        public void BookmarkedTest()
        {
            // TODO unit test for the property 'Bookmarked'
        }
        /// <summary>
        /// Test the property 'ResolvedPermissions'
        /// </summary>
        [Fact]
        public void ResolvedPermissionsTest()
        {
            // TODO unit test for the property 'ResolvedPermissions'
        }
        /// <summary>
        /// Test the property 'ResolvedReadOnly'
        /// </summary>
        [Fact]
        public void ResolvedReadOnlyTest()
        {
            // TODO unit test for the property 'ResolvedReadOnly'
        }
        /// <summary>
        /// Test the property 'RecycleBinPath'
        /// </summary>
        [Fact]
        public void RecycleBinPathTest()
        {
            // TODO unit test for the property 'RecycleBinPath'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Directory'
        /// </summary>
        [Fact]
        public void DirectoryTest()
        {
            // TODO unit test for the property 'Directory'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'LongDescription'
        /// </summary>
        [Fact]
        public void LongDescriptionTest()
        {
            // TODO unit test for the property 'LongDescription'
        }
        /// <summary>
        /// Test the property 'IsTemplate'
        /// </summary>
        [Fact]
        public void IsTemplateTest()
        {
            // TODO unit test for the property 'IsTemplate'
        }
        /// <summary>
        /// Test the property 'LastLogin'
        /// </summary>
        [Fact]
        public void LastLoginTest()
        {
            // TODO unit test for the property 'LastLogin'
        }
        /// <summary>
        /// Test the property 'Active'
        /// </summary>
        [Fact]
        public void ActiveTest()
        {
            // TODO unit test for the property 'Active'
        }
        /// <summary>
        /// Test the property 'MacProtocol'
        /// </summary>
        [Fact]
        public void MacProtocolTest()
        {
            // TODO unit test for the property 'MacProtocol'
        }
        /// <summary>
        /// Test the property 'WinProtocol'
        /// </summary>
        [Fact]
        public void WinProtocolTest()
        {
            // TODO unit test for the property 'WinProtocol'
        }
        /// <summary>
        /// Test the property 'WinDrive'
        /// </summary>
        [Fact]
        public void WinDriveTest()
        {
            // TODO unit test for the property 'WinDrive'
        }
        /// <summary>
        /// Test the property 'LinuxProtocol'
        /// </summary>
        [Fact]
        public void LinuxProtocolTest()
        {
            // TODO unit test for the property 'LinuxProtocol'
        }
        /// <summary>
        /// Test the property 'LinuxMountpoint'
        /// </summary>
        [Fact]
        public void LinuxMountpointTest()
        {
            // TODO unit test for the property 'LinuxMountpoint'
        }
        /// <summary>
        /// Test the property 'ShareName'
        /// </summary>
        [Fact]
        public void ShareNameTest()
        {
            // TODO unit test for the property 'ShareName'
        }
        /// <summary>
        /// Test the property 'ShareNfs'
        /// </summary>
        [Fact]
        public void ShareNfsTest()
        {
            // TODO unit test for the property 'ShareNfs'
        }
        /// <summary>
        /// Test the property 'ShareAfp'
        /// </summary>
        [Fact]
        public void ShareAfpTest()
        {
            // TODO unit test for the property 'ShareAfp'
        }
        /// <summary>
        /// Test the property 'SharingHidden'
        /// </summary>
        [Fact]
        public void SharingHiddenTest()
        {
            // TODO unit test for the property 'SharingHidden'
        }
        /// <summary>
        /// Test the property 'SharingRequireLogin'
        /// </summary>
        [Fact]
        public void SharingRequireLoginTest()
        {
            // TODO unit test for the property 'SharingRequireLogin'
        }
        /// <summary>
        /// Test the property 'SharingReadOnly'
        /// </summary>
        [Fact]
        public void SharingReadOnlyTest()
        {
            // TODO unit test for the property 'SharingReadOnly'
        }
        /// <summary>
        /// Test the property 'SharingAllowExecute'
        /// </summary>
        [Fact]
        public void SharingAllowExecuteTest()
        {
            // TODO unit test for the property 'SharingAllowExecute'
        }
        /// <summary>
        /// Test the property 'QuotaSizeHard'
        /// </summary>
        [Fact]
        public void QuotaSizeHardTest()
        {
            // TODO unit test for the property 'QuotaSizeHard'
        }
        /// <summary>
        /// Test the property 'QuotaSizeSoft'
        /// </summary>
        [Fact]
        public void QuotaSizeSoftTest()
        {
            // TODO unit test for the property 'QuotaSizeSoft'
        }
        /// <summary>
        /// Test the property 'Affinity'
        /// </summary>
        [Fact]
        public void AffinityTest()
        {
            // TODO unit test for the property 'Affinity'
        }
        /// <summary>
        /// Test the property 'EmulateAvid'
        /// </summary>
        [Fact]
        public void EmulateAvidTest()
        {
            // TODO unit test for the property 'EmulateAvid'
        }
        /// <summary>
        /// Test the property 'EmulateCapture'
        /// </summary>
        [Fact]
        public void EmulateCaptureTest()
        {
            // TODO unit test for the property 'EmulateCapture'
        }
        /// <summary>
        /// Test the property 'EmulatePreopen'
        /// </summary>
        [Fact]
        public void EmulatePreopenTest()
        {
            // TODO unit test for the property 'EmulatePreopen'
        }
        /// <summary>
        /// Test the property 'EmulateNtfsStreams'
        /// </summary>
        [Fact]
        public void EmulateNtfsStreamsTest()
        {
            // TODO unit test for the property 'EmulateNtfsStreams'
        }
        /// <summary>
        /// Test the property 'EmulateRecycleBin'
        /// </summary>
        [Fact]
        public void EmulateRecycleBinTest()
        {
            // TODO unit test for the property 'EmulateRecycleBin'
        }
        /// <summary>
        /// Test the property 'EmulateFruit'
        /// </summary>
        [Fact]
        public void EmulateFruitTest()
        {
            // TODO unit test for the property 'EmulateFruit'
        }
        /// <summary>
        /// Test the property 'SmbExtraConfig'
        /// </summary>
        [Fact]
        public void SmbExtraConfigTest()
        {
            // TODO unit test for the property 'SmbExtraConfig'
        }
        /// <summary>
        /// Test the property 'AfpExtraConfig'
        /// </summary>
        [Fact]
        public void AfpExtraConfigTest()
        {
            // TODO unit test for the property 'AfpExtraConfig'
        }
        /// <summary>
        /// Test the property 'RecycleBinExclude'
        /// </summary>
        [Fact]
        public void RecycleBinExcludeTest()
        {
            // TODO unit test for the property 'RecycleBinExclude'
        }
        /// <summary>
        /// Test the property 'IsExternal'
        /// </summary>
        [Fact]
        public void IsExternalTest()
        {
            // TODO unit test for the property 'IsExternal'
        }
        /// <summary>
        /// Test the property 'ExternalMacUrl'
        /// </summary>
        [Fact]
        public void ExternalMacUrlTest()
        {
            // TODO unit test for the property 'ExternalMacUrl'
        }
        /// <summary>
        /// Test the property 'ExternalWinUrl'
        /// </summary>
        [Fact]
        public void ExternalWinUrlTest()
        {
            // TODO unit test for the property 'ExternalWinUrl'
        }
        /// <summary>
        /// Test the property 'ExternalLinuxUrl'
        /// </summary>
        [Fact]
        public void ExternalLinuxUrlTest()
        {
            // TODO unit test for the property 'ExternalLinuxUrl'
        }
        /// <summary>
        /// Test the property 'AllowSymlinks'
        /// </summary>
        [Fact]
        public void AllowSymlinksTest()
        {
            // TODO unit test for the property 'AllowSymlinks'
        }
        /// <summary>
        /// Test the property 'RwPermissionPriority'
        /// </summary>
        [Fact]
        public void RwPermissionPriorityTest()
        {
            // TODO unit test for the property 'RwPermissionPriority'
        }
        /// <summary>
        /// Test the property 'Template'
        /// </summary>
        [Fact]
        public void TemplateTest()
        {
            // TODO unit test for the property 'Template'
        }
        /// <summary>
        /// Test the property 'HomeFor'
        /// </summary>
        [Fact]
        public void HomeForTest()
        {
            // TODO unit test for the property 'HomeFor'
        }

    }

}
