/*
 * ELEMENTS API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = ElementsSDK.Client.OpenAPIDateConverter;

namespace ElementsSDK.Model
{
    /// <summary>
    /// ArchiveEndpointRequest
    /// </summary>
    [DataContract(Name = "ArchiveEndpointRequest")]
    public partial class ArchiveEndpointRequest : IEquatable<ArchiveEndpointRequest>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ArchiveEndpointRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ArchiveEndpointRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ArchiveEndpointRequest" /> class.
        /// </summary>
        /// <param name="source">source (required).</param>
        /// <param name="startDate">startDate (required).</param>
        /// <param name="name">name (required).</param>
        /// <param name="group">group.</param>
        /// <param name="group2">group2.</param>
        /// <param name="export">export.</param>
        /// <param name="export2">export2.</param>
        public ArchiveEndpointRequest(List<TapeJobSource> source = default(List<TapeJobSource>), DateTime startDate = default(DateTime), string name = default(string), int group = default(int), int? group2 = default(int?), bool export = default(bool), bool? export2 = default(bool?))
        {
            // to ensure "source" is required (not null)
            this.Source = source ?? throw new ArgumentNullException("source is a required property for ArchiveEndpointRequest and cannot be null");
            this.StartDate = startDate;
            // to ensure "name" is required (not null)
            this.Name = name ?? throw new ArgumentNullException("name is a required property for ArchiveEndpointRequest and cannot be null");
            this.Group = group;
            this.Group2 = group2;
            this.Export = export;
            this.Export2 = export2;
        }

        /// <summary>
        /// Gets or Sets Source
        /// </summary>
        [DataMember(Name = "source", IsRequired = true, EmitDefaultValue = false)]
        public List<TapeJobSource> Source { get; set; }

        /// <summary>
        /// Gets or Sets StartDate
        /// </summary>
        [DataMember(Name = "start_date", IsRequired = true, EmitDefaultValue = false)]
        public DateTime StartDate { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name = "name", IsRequired = true, EmitDefaultValue = false)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets Group
        /// </summary>
        [DataMember(Name = "group", EmitDefaultValue = false)]
        public int Group { get; set; }

        /// <summary>
        /// Gets or Sets Group2
        /// </summary>
        [DataMember(Name = "group2", EmitDefaultValue = true)]
        public int? Group2 { get; set; }

        /// <summary>
        /// Gets or Sets Export
        /// </summary>
        [DataMember(Name = "export", EmitDefaultValue = true)]
        public bool Export { get; set; }

        /// <summary>
        /// Gets or Sets Export2
        /// </summary>
        [DataMember(Name = "export2", EmitDefaultValue = true)]
        public bool? Export2 { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ArchiveEndpointRequest {\n");
            sb.Append("  Source: ").Append(Source).Append("\n");
            sb.Append("  StartDate: ").Append(StartDate).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Group: ").Append(Group).Append("\n");
            sb.Append("  Group2: ").Append(Group2).Append("\n");
            sb.Append("  Export: ").Append(Export).Append("\n");
            sb.Append("  Export2: ").Append(Export2).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ArchiveEndpointRequest);
        }

        /// <summary>
        /// Returns true if ArchiveEndpointRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of ArchiveEndpointRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ArchiveEndpointRequest input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Source == input.Source ||
                    this.Source != null &&
                    input.Source != null &&
                    this.Source.SequenceEqual(input.Source)
                ) && 
                (
                    this.StartDate == input.StartDate ||
                    (this.StartDate != null &&
                    this.StartDate.Equals(input.StartDate))
                ) && 
                (
                    this.Name == input.Name ||
                    (this.Name != null &&
                    this.Name.Equals(input.Name))
                ) && 
                (
                    this.Group == input.Group ||
                    this.Group.Equals(input.Group)
                ) && 
                (
                    this.Group2 == input.Group2 ||
                    (this.Group2 != null &&
                    this.Group2.Equals(input.Group2))
                ) && 
                (
                    this.Export == input.Export ||
                    this.Export.Equals(input.Export)
                ) && 
                (
                    this.Export2 == input.Export2 ||
                    (this.Export2 != null &&
                    this.Export2.Equals(input.Export2))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Source != null)
                    hashCode = hashCode * 59 + this.Source.GetHashCode();
                if (this.StartDate != null)
                    hashCode = hashCode * 59 + this.StartDate.GetHashCode();
                if (this.Name != null)
                    hashCode = hashCode * 59 + this.Name.GetHashCode();
                hashCode = hashCode * 59 + this.Group.GetHashCode();
                if (this.Group2 != null)
                    hashCode = hashCode * 59 + this.Group2.GetHashCode();
                hashCode = hashCode * 59 + this.Export.GetHashCode();
                if (this.Export2 != null)
                    hashCode = hashCode * 59 + this.Export2.GetHashCode();
                return hashCode;
            }
        }

    }

}
