/*
 * ELEMENTS API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = ElementsSDK.Client.OpenAPIDateConverter;

namespace ElementsSDK.Model
{
    /// <summary>
    /// AssetRatingPartialUpdate
    /// </summary>
    [DataContract(Name = "AssetRatingPartialUpdate")]
    public partial class AssetRatingPartialUpdate : IEquatable<AssetRatingPartialUpdate>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AssetRatingPartialUpdate" /> class.
        /// </summary>
        /// <param name="user">user.</param>
        /// <param name="rating">rating.</param>
        /// <param name="asset">asset.</param>
        public AssetRatingPartialUpdate(ElementsUserMiniReference user = default(ElementsUserMiniReference), int rating = default(int), int asset = default(int))
        {
            this.User = user;
            this.Rating = rating;
            this.Asset = asset;
        }

        /// <summary>
        /// Gets or Sets User
        /// </summary>
        [DataMember(Name = "user", EmitDefaultValue = false)]
        public ElementsUserMiniReference User { get; set; }

        /// <summary>
        /// Gets or Sets Rating
        /// </summary>
        [DataMember(Name = "rating", EmitDefaultValue = false)]
        public int Rating { get; set; }

        /// <summary>
        /// Gets or Sets Asset
        /// </summary>
        [DataMember(Name = "asset", EmitDefaultValue = false)]
        public int Asset { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class AssetRatingPartialUpdate {\n");
            sb.Append("  User: ").Append(User).Append("\n");
            sb.Append("  Rating: ").Append(Rating).Append("\n");
            sb.Append("  Asset: ").Append(Asset).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as AssetRatingPartialUpdate);
        }

        /// <summary>
        /// Returns true if AssetRatingPartialUpdate instances are equal
        /// </summary>
        /// <param name="input">Instance of AssetRatingPartialUpdate to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(AssetRatingPartialUpdate input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.User == input.User ||
                    (this.User != null &&
                    this.User.Equals(input.User))
                ) && 
                (
                    this.Rating == input.Rating ||
                    this.Rating.Equals(input.Rating)
                ) && 
                (
                    this.Asset == input.Asset ||
                    this.Asset.Equals(input.Asset)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.User != null)
                    hashCode = hashCode * 59 + this.User.GetHashCode();
                hashCode = hashCode * 59 + this.Rating.GetHashCode();
                hashCode = hashCode * 59 + this.Asset.GetHashCode();
                return hashCode;
            }
        }

    }

}
