/*
 * ELEMENTS API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = ElementsSDK.Client.OpenAPIDateConverter;

namespace ElementsSDK.Model
{
    /// <summary>
    /// EnableTOTPRequest
    /// </summary>
    [DataContract(Name = "EnableTOTPRequest")]
    public partial class EnableTOTPRequest : IEquatable<EnableTOTPRequest>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EnableTOTPRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected EnableTOTPRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="EnableTOTPRequest" /> class.
        /// </summary>
        /// <param name="key">key (required).</param>
        /// <param name="otp">otp (required).</param>
        public EnableTOTPRequest(string key = default(string), string otp = default(string))
        {
            // to ensure "key" is required (not null)
            this.Key = key ?? throw new ArgumentNullException("key is a required property for EnableTOTPRequest and cannot be null");
            // to ensure "otp" is required (not null)
            this.Otp = otp ?? throw new ArgumentNullException("otp is a required property for EnableTOTPRequest and cannot be null");
        }

        /// <summary>
        /// Gets or Sets Key
        /// </summary>
        [DataMember(Name = "key", IsRequired = true, EmitDefaultValue = false)]
        public string Key { get; set; }

        /// <summary>
        /// Gets or Sets Otp
        /// </summary>
        [DataMember(Name = "otp", IsRequired = true, EmitDefaultValue = false)]
        public string Otp { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class EnableTOTPRequest {\n");
            sb.Append("  Key: ").Append(Key).Append("\n");
            sb.Append("  Otp: ").Append(Otp).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as EnableTOTPRequest);
        }

        /// <summary>
        /// Returns true if EnableTOTPRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of EnableTOTPRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(EnableTOTPRequest input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Key == input.Key ||
                    (this.Key != null &&
                    this.Key.Equals(input.Key))
                ) && 
                (
                    this.Otp == input.Otp ||
                    (this.Otp != null &&
                    this.Otp.Equals(input.Otp))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Key != null)
                    hashCode = hashCode * 59 + this.Key.GetHashCode();
                if (this.Otp != null)
                    hashCode = hashCode * 59 + this.Otp.GetHashCode();
                return hashCode;
            }
        }

    }

}
