/*
 * ELEMENTS API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = ElementsSDK.Client.OpenAPIDateConverter;

namespace ElementsSDK.Model
{
    /// <summary>
    /// FileSizeDistribution
    /// </summary>
    [DataContract(Name = "FileSizeDistribution")]
    public partial class FileSizeDistribution : IEquatable<FileSizeDistribution>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="FileSizeDistribution" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected FileSizeDistribution() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="FileSizeDistribution" /> class.
        /// </summary>
        /// <param name="distribution">distribution (required).</param>
        public FileSizeDistribution(List<FileSizeDistributionItem> distribution = default(List<FileSizeDistributionItem>))
        {
            // to ensure "distribution" is required (not null)
            this.Distribution = distribution ?? throw new ArgumentNullException("distribution is a required property for FileSizeDistribution and cannot be null");
        }

        /// <summary>
        /// Gets or Sets Distribution
        /// </summary>
        [DataMember(Name = "distribution", IsRequired = true, EmitDefaultValue = false)]
        public List<FileSizeDistributionItem> Distribution { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class FileSizeDistribution {\n");
            sb.Append("  Distribution: ").Append(Distribution).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as FileSizeDistribution);
        }

        /// <summary>
        /// Returns true if FileSizeDistribution instances are equal
        /// </summary>
        /// <param name="input">Instance of FileSizeDistribution to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(FileSizeDistribution input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Distribution == input.Distribution ||
                    this.Distribution != null &&
                    input.Distribution != null &&
                    this.Distribution.SequenceEqual(input.Distribution)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Distribution != null)
                    hashCode = hashCode * 59 + this.Distribution.GetHashCode();
                return hashCode;
            }
        }

    }

}
