/*
 * ELEMENTS API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = ElementsSDK.Client.OpenAPIDateConverter;

namespace ElementsSDK.Model
{
    /// <summary>
    /// ImpersonationEndpointRequest
    /// </summary>
    [DataContract(Name = "ImpersonationEndpointRequest")]
    public partial class ImpersonationEndpointRequest : IEquatable<ImpersonationEndpointRequest>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ImpersonationEndpointRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ImpersonationEndpointRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ImpersonationEndpointRequest" /> class.
        /// </summary>
        /// <param name="user">user (required).</param>
        public ImpersonationEndpointRequest(int user = default(int))
        {
            this.User = user;
        }

        /// <summary>
        /// Gets or Sets User
        /// </summary>
        [DataMember(Name = "user", IsRequired = true, EmitDefaultValue = false)]
        public int User { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ImpersonationEndpointRequest {\n");
            sb.Append("  User: ").Append(User).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ImpersonationEndpointRequest);
        }

        /// <summary>
        /// Returns true if ImpersonationEndpointRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of ImpersonationEndpointRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ImpersonationEndpointRequest input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.User == input.User ||
                    this.User.Equals(input.User)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = hashCode * 59 + this.User.GetHashCode();
                return hashCode;
            }
        }

    }

}
