/*
 * ELEMENTS API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = ElementsSDK.Client.OpenAPIDateConverter;

namespace ElementsSDK.Model
{
    /// <summary>
    /// LDAPServerGroups
    /// </summary>
    [DataContract(Name = "LDAPServerGroups")]
    public partial class LDAPServerGroups : IEquatable<LDAPServerGroups>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="LDAPServerGroups" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected LDAPServerGroups() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="LDAPServerGroups" /> class.
        /// </summary>
        /// <param name="groups">groups (required).</param>
        public LDAPServerGroups(List<LDAPServerGroup> groups = default(List<LDAPServerGroup>))
        {
            // to ensure "groups" is required (not null)
            this.Groups = groups ?? throw new ArgumentNullException("groups is a required property for LDAPServerGroups and cannot be null");
        }

        /// <summary>
        /// Gets or Sets Groups
        /// </summary>
        [DataMember(Name = "groups", IsRequired = true, EmitDefaultValue = false)]
        public List<LDAPServerGroup> Groups { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class LDAPServerGroups {\n");
            sb.Append("  Groups: ").Append(Groups).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as LDAPServerGroups);
        }

        /// <summary>
        /// Returns true if LDAPServerGroups instances are equal
        /// </summary>
        /// <param name="input">Instance of LDAPServerGroups to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(LDAPServerGroups input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Groups == input.Groups ||
                    this.Groups != null &&
                    input.Groups != null &&
                    this.Groups.SequenceEqual(input.Groups)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Groups != null)
                    hashCode = hashCode * 59 + this.Groups.GetHashCode();
                return hashCode;
            }
        }

    }

}
