/*
 * ELEMENTS API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = ElementsSDK.Client.OpenAPIDateConverter;

namespace ElementsSDK.Model
{
    /// <summary>
    /// SlackMessage
    /// </summary>
    [DataContract(Name = "SlackMessage")]
    public partial class SlackMessage : IEquatable<SlackMessage>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SlackMessage" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected SlackMessage() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="SlackMessage" /> class.
        /// </summary>
        /// <param name="recipient">recipient (required).</param>
        /// <param name="text">text (required).</param>
        /// <param name="username">username.</param>
        /// <param name="emoji">emoji.</param>
        public SlackMessage(string recipient = default(string), string text = default(string), string username = default(string), string emoji = default(string))
        {
            // to ensure "recipient" is required (not null)
            this.Recipient = recipient ?? throw new ArgumentNullException("recipient is a required property for SlackMessage and cannot be null");
            // to ensure "text" is required (not null)
            this.Text = text ?? throw new ArgumentNullException("text is a required property for SlackMessage and cannot be null");
            this.Username = username;
            this.Emoji = emoji;
        }

        /// <summary>
        /// Gets or Sets Recipient
        /// </summary>
        [DataMember(Name = "recipient", IsRequired = true, EmitDefaultValue = false)]
        public string Recipient { get; set; }

        /// <summary>
        /// Gets or Sets Text
        /// </summary>
        [DataMember(Name = "text", IsRequired = true, EmitDefaultValue = false)]
        public string Text { get; set; }

        /// <summary>
        /// Gets or Sets Username
        /// </summary>
        [DataMember(Name = "username", EmitDefaultValue = true)]
        public string Username { get; set; }

        /// <summary>
        /// Gets or Sets Emoji
        /// </summary>
        [DataMember(Name = "emoji", EmitDefaultValue = true)]
        public string Emoji { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class SlackMessage {\n");
            sb.Append("  Recipient: ").Append(Recipient).Append("\n");
            sb.Append("  Text: ").Append(Text).Append("\n");
            sb.Append("  Username: ").Append(Username).Append("\n");
            sb.Append("  Emoji: ").Append(Emoji).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as SlackMessage);
        }

        /// <summary>
        /// Returns true if SlackMessage instances are equal
        /// </summary>
        /// <param name="input">Instance of SlackMessage to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SlackMessage input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Recipient == input.Recipient ||
                    (this.Recipient != null &&
                    this.Recipient.Equals(input.Recipient))
                ) && 
                (
                    this.Text == input.Text ||
                    (this.Text != null &&
                    this.Text.Equals(input.Text))
                ) && 
                (
                    this.Username == input.Username ||
                    (this.Username != null &&
                    this.Username.Equals(input.Username))
                ) && 
                (
                    this.Emoji == input.Emoji ||
                    (this.Emoji != null &&
                    this.Emoji.Equals(input.Emoji))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Recipient != null)
                    hashCode = hashCode * 59 + this.Recipient.GetHashCode();
                if (this.Text != null)
                    hashCode = hashCode * 59 + this.Text.GetHashCode();
                if (this.Username != null)
                    hashCode = hashCode * 59 + this.Username.GetHashCode();
                if (this.Emoji != null)
                    hashCode = hashCode * 59 + this.Emoji.GetHashCode();
                return hashCode;
            }
        }

    }

}
