/*
 * ELEMENTS API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = ElementsSDK.Client.OpenAPIDateConverter;

namespace ElementsSDK.Model
{
    /// <summary>
    /// UploadChunkEndpointRequest
    /// </summary>
    [DataContract(Name = "UploadChunkEndpointRequest")]
    public partial class UploadChunkEndpointRequest : IEquatable<UploadChunkEndpointRequest>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UploadChunkEndpointRequest" /> class.
        /// </summary>
        /// <param name="uploadId">uploadId.</param>
        /// <param name="chunkNumber">chunkNumber.</param>
        /// <param name="totalChunks">totalChunks.</param>
        public UploadChunkEndpointRequest(string uploadId = default(string), int chunkNumber = default(int), int totalChunks = default(int))
        {
            this.UploadId = uploadId;
            this.ChunkNumber = chunkNumber;
            this.TotalChunks = totalChunks;
        }

        /// <summary>
        /// Gets or Sets UploadId
        /// </summary>
        [DataMember(Name = "upload_id", EmitDefaultValue = false)]
        public string UploadId { get; set; }

        /// <summary>
        /// Gets or Sets ChunkNumber
        /// </summary>
        [DataMember(Name = "chunk_number", EmitDefaultValue = false)]
        public int ChunkNumber { get; set; }

        /// <summary>
        /// Gets or Sets TotalChunks
        /// </summary>
        [DataMember(Name = "total_chunks", EmitDefaultValue = false)]
        public int TotalChunks { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class UploadChunkEndpointRequest {\n");
            sb.Append("  UploadId: ").Append(UploadId).Append("\n");
            sb.Append("  ChunkNumber: ").Append(ChunkNumber).Append("\n");
            sb.Append("  TotalChunks: ").Append(TotalChunks).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as UploadChunkEndpointRequest);
        }

        /// <summary>
        /// Returns true if UploadChunkEndpointRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of UploadChunkEndpointRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(UploadChunkEndpointRequest input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.UploadId == input.UploadId ||
                    (this.UploadId != null &&
                    this.UploadId.Equals(input.UploadId))
                ) && 
                (
                    this.ChunkNumber == input.ChunkNumber ||
                    this.ChunkNumber.Equals(input.ChunkNumber)
                ) && 
                (
                    this.TotalChunks == input.TotalChunks ||
                    this.TotalChunks.Equals(input.TotalChunks)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.UploadId != null)
                    hashCode = hashCode * 59 + this.UploadId.GetHashCode();
                hashCode = hashCode * 59 + this.ChunkNumber.GetHashCode();
                hashCode = hashCode * 59 + this.TotalChunks.GetHashCode();
                return hashCode;
            }
        }

    }

}
