/*
 * ELEMENTS API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = ElementsSDK.Client.OpenAPIDateConverter;

namespace ElementsSDK.Model
{
    /// <summary>
    /// VolumeSNFSStatus
    /// </summary>
    [DataContract(Name = "VolumeSNFSStatus")]
    public partial class VolumeSNFSStatus : IEquatable<VolumeSNFSStatus>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="VolumeSNFSStatus" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected VolumeSNFSStatus() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="VolumeSNFSStatus" /> class.
        /// </summary>
        /// <param name="stripeGroups">stripeGroups (required).</param>
        public VolumeSNFSStatus(List<SNFSStripeGroup> stripeGroups = default(List<SNFSStripeGroup>))
        {
            // to ensure "stripeGroups" is required (not null)
            this.StripeGroups = stripeGroups ?? throw new ArgumentNullException("stripeGroups is a required property for VolumeSNFSStatus and cannot be null");
        }

        /// <summary>
        /// Gets or Sets StripeGroups
        /// </summary>
        [DataMember(Name = "stripe_groups", IsRequired = true, EmitDefaultValue = false)]
        public List<SNFSStripeGroup> StripeGroups { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class VolumeSNFSStatus {\n");
            sb.Append("  StripeGroups: ").Append(StripeGroups).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as VolumeSNFSStatus);
        }

        /// <summary>
        /// Returns true if VolumeSNFSStatus instances are equal
        /// </summary>
        /// <param name="input">Instance of VolumeSNFSStatus to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(VolumeSNFSStatus input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.StripeGroups == input.StripeGroups ||
                    this.StripeGroups != null &&
                    input.StripeGroups != null &&
                    this.StripeGroups.SequenceEqual(input.StripeGroups)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.StripeGroups != null)
                    hashCode = hashCode * 59 + this.StripeGroups.GetHashCode();
                return hashCode;
            }
        }

    }

}
